### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by BenoitDuffez** [hillaryychan/ulauncher-fzf#20]
Hi, I wanted to try this but I couldn't make it work:

```
$ ulauncher
Traceback (most recent call last):
  File "/home/bdu/.local/share/ulauncher/extensions/com.github.hillaryychan.ulauncher-fzf/main.py", line 18, in <module>
    BinNames = dict[str, str]
TypeError: 'type' object is not subscriptable
2022-03-01 14:29:02,888 | ERROR | ulauncher.api.server.ExtensionRunner: _run_process() | Extension "com.github.hillaryychan.ulauncher-fzf" exited instantly with code 1
2022-03-01 14:29:02,888 | ERROR | ulauncher.api.server.ExtensionRunner: _run_process() | Extension "com.github.hillaryychan.ulauncher-fzf" failed with an error: TypeError: 'type' object is not subscriptable
```

What did I miss?

```
$ python --version
Python 2.7.17
$ python3 --version
Python 3.6.9
$ fd --version
fd 8.3.1
$ fzf --version
0.29.0 (dc975e8)
$ ulauncher --version
ulauncher 5.14.3
```

Running Elementary OS:
```
$ cat /etc/*release
DISTRIB_ID=elementary
DISTRIB_RELEASE=5.1.7
DISTRIB_CODENAME=hera
DISTRIB_DESCRIPTION="elementary OS 5.1.7 Hera"
NAME="elementary OS"
VERSION="5.1.7 Hera"
ID=elementary
ID_LIKE=ubuntu
PRETTY_NAME="elementary OS 5.1.7 Hera"
LOGO=distributor-logo
VERSION_ID="5.1.7"
HOME_URL="https://elementary.io/"
SUPPORT_URL="https://elementary.io/support"
BUG_REPORT_URL="https://github.com/elementary/os/issues/new"
PRIVACY_POLICY_URL="https://elementary.io/privacy-policy"
VERSION_CODENAME=hera
UBUNTU_CODENAME=bionic
```

**Comment by hillaryychan** [comment]
Hello,

This is probably because of my latest change for adding type hints to function definitions uses `dict` instead of `typing.Dict`. `dict` is a built-in type for Python 3.9 onwards with them deprecating `typing.Dict`

I'll make a fix for this soon

**Comment by hillaryychan** [comment]
@BenoitDuffez Can you update your the extension and see if it works now?

**Comment by BenoitDuffez** [comment]
Actually this convinced me to upgrade my system... took me too many hours and a lot of struggle with aptitude... and now with Elementary OS 6.1 (latest, Ubuntu focal)... I'm on python 3.8 lol. I had expected to have 3.9. :laughing: 

Anyway, I have updated the app and it crashes elsewhere now:

```
$ ulauncher
Traceback (most recent call last):
  File "/home/bdu/.local/share/ulauncher/extensions/com.github.hillaryychan.ulauncher-fzf/main.py", line 34, in <module>
    def no_op_result_items(msgs: list[str], icon: str = "icon") -> RenderResultListAction:
TypeError: 'type' object is not subscriptable
2022-03-02 14:56:39,521 | ERROR | ulauncher.api.server.ExtensionRunner: _run_process() | Extension "com.github.hillaryychan.ulauncher-fzf" exited instantly with code 1
2022-03-02 14:56:39,521 | ERROR | ulauncher.api.server.ExtensionRunner: _run_process() | Extension "com.github.hillaryychan.ulauncher-fzf" failed with an error: TypeError: 'type' object is not subscriptable
```

Env:

```
$ python3 --version
Python 3.8.10
$ cat /etc/*release
DISTRIB_ID=elementary
DISTRIB_RELEASE=6.1
DISTRIB_CODENAME=jolnir
DISTRIB_DESCRIPTION="elementary OS 6 Jólnir"
NAME="elementary OS"
VERSION="6.1 Jólnir"
ID=elementary
ID_LIKE=ubuntu
PRETTY_NAME="elementary OS 6.1 Jólnir"
LOGO=distributor-logo
VERSION_ID="6.1"
HOME_URL="https://elementary.io/"
DOCUMENTATION_URL="https://elementary.io/docs/learning-the-basics"
SUPPORT_URL="https://elementary.io/support"
BUG_REPORT_URL="https://github.com/elementary/triage/issues/new"
PRIVACY_POLICY_URL="https://elementary.io/privacy-policy"
VERSION_CODENAME=jolnir
UBUNTU_CODENAME=focal
```

**Comment by BenoitDuffez** [comment]
I dug a little bit better and you have strict type declarations that fail with `list[str]` on lines 34, 60, 79, 115 and 132. If I knew how to write Python I'd submit a PR but I don't :)

With this, it works.

Unrelated question: do you know if ulauncher would allow you to trigger on any request (eg without the keyword search)? I tried with no keyword (instead of `fzf`), but it doesn't work. I reduced this to a single `f` for faster results.

Thank you for your work, this is awesome.

**Comment by hillaryychan** [comment]
Ahh, yep that's on me. I forgot to check for other built-in types that are superseding `typing` Generics. Should be fixed now.

Let me know if there are any more issues

**Comment by BenoitDuffez** [comment]
I'm sorry, he's still grumpy:

```
$ ulauncher
Traceback (most recent call last):
  File "/home/bdu/.local/share/ulauncher/extensions/com.github.hillaryychan.ulauncher-fzf/main.py", line 46, in <module>
    class FuzzyFinderExtension(Extension):
  File "/home/bdu/.local/share/ulauncher/extensions/com.github.hillaryychan.ulauncher-fzf/main.py", line 60, in FuzzyFinderExtension
    def get_binaries(self) -> tuple[BinNames, List[str]]:
TypeError: 'type' object is not subscriptable
2022-03-03 12:06:26,653 | ERROR | ulauncher.api.server.ExtensionRunner: _run_process() | Extension "com.github.hillaryychan.ulauncher-fzf" exited instantly with code 1
2022-03-03 12:06:26,654 | ERROR | ulauncher.api.server.ExtensionRunner: _run_process() | Extension "com.github.hillaryychan.ulauncher-fzf" failed with an error: TypeError: 'type' object is not subscriptable
```

**Comment by hillaryychan** [comment]
I didn't realise there were this many generic types being replaced :sweat_smile: 

I've merged an update. 

If there are anymore issues, I think I will just remove the type hints completely

**Comment by BenoitDuffez** [comment]
Haha sorry about all that. It works like a charm now.

Please don't remove type hints. I wish all languages were strong typed, creates so many bugs and maintenance issues down the road. So if Python brings type hints, let's all use them.
